load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "com_github_edschouten_rules_elm",
    path = "../external/com_github_edschouten_rules_elm",
)

load("@com_github_edschouten_rules_elm//elm:deps.bzl", "elm_register_toolchains")
load("@com_github_edschouten_rules_elm//repository:def.bzl", "elm_repository")
elm_register_toolchains()

rules_nixpkgs_version = "ae5346bb83c7a7b1e2b5dd3b4539f43953376ec8"
http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "fee4136ed85b50d6a6ea69cfb34fbd355821b0448791bb3c0b7947e70013beeb",
    strip_prefix = "rules_nixpkgs-%s" % rules_nixpkgs_version,
    urls = [
        # "https://github.com/tweag/rules_nixpkgs/archive/ae5346bb83c7a7b1e2b5dd3b4539f43953376ec8.tar.gz"
        "https://github.com/tweag/rules_nixpkgs/archive/%s.tar.gz" % rules_nixpkgs_version
    ],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "b01f170580f646ee3cde1ea4c117d00e561afaf3c59eda604cf09194a824ff10",
    strip_prefix = "rules_nixpkgs-0.9.0",
    urls = ["curl -L https://github.com/tweag/prules_nixpkgs/archive/refs/tags/v0.9.0.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_local_repository", "nixpkgs_package")

nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//:nixpkgs.nix",
    nix_file_deps = ["//:nixpkgs.json"],
)

nixpkgs_package(
    name ="uglifyjs",
    attribute_path = "nodePackages.uglify-js",
    repository = "@nixpkgs",
)

elm_repository(
        name = "elm_package_elm_core",
        sha256 = "6e37b11c88c89a68d19d0c7625f1ef39ed70c59e443def95e4de98d6748c80a7",
        strip_prefix = "core-1.0.5",
        urls = ["https://github.com/elm/core/archive/1.0.5.tar.gz"],
)
elm_repository(
    name = "elm_package_elm_json",
    sha256 = "d0635f33137e4ad3fc323f96ba280e45dc41afa51076c53d9f04fd92c2cf5c4e",
    strip_prefix = "json-1.1.3",
    urls = ["https://github.com/elm/json/archive/1.1.3.tar.gz"],
)
