load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "com_github_edschouten_rules_elm",
    path = "../external/com_github_edschouten_rules_elm",
)

load("@com_github_edschouten_rules_elm//elm:deps.bzl", "elm_register_toolchains")
load("@com_github_edschouten_rules_elm//repository:def.bzl", "elm_repository")
elm_register_toolchains()

rules_nixpkgs_version = "ae5346bb83c7a7b1e2b5dd3b4539f43953376ec8"
http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "fee4136ed85b50d6a6ea69cfb34fbd355821b0448791bb3c0b7947e70013beeb",
    strip_prefix = "rules_nixpkgs-%s" % rules_nixpkgs_version,
    urls = [
        # "https://github.com/tweag/rules_nixpkgs/archive/ae5346bb83c7a7b1e2b5dd3b4539f43953376ec8.tar.gz"
        "https://github.com/tweag/rules_nixpkgs/archive/%s.tar.gz" % rules_nixpkgs_version
    ],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "b01f170580f646ee3cde1ea4c117d00e561afaf3c59eda604cf09194a824ff10",
    strip_prefix = "rules_nixpkgs-0.9.0",
    urls = ["curl -L https://github.com/tweag/prules_nixpkgs/archive/refs/tags/v0.9.0.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
rules_nixpkgs_dependencies()
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_local_repository", "nixpkgs_package")

nixpkgs_local_repository(
    name = "nixpkgs",
    nix_file = "//:nixpkgs.nix",
    nix_file_deps = ["//:nixpkgs.json"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_nodejs_configure_platforms")
nixpkgs_nodejs_configure_platforms(
  name = "nixpkgs-nodejs",
  repository = "@nixpkgs",
)


http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "dcc55f810142b6cf46a44d0180a5a7fb923c04a5061e2e8d8eb05ccccc60864b",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/5.8.0/rules_nodejs-5.8.0.tar.gz"],
)

load("@build_bazel_rules_nodejs//:index.bzl", "npm_install")
npm_install(
    name = "npm",
    exports_directories_only = True,
    node_repository = "nixpkgs-nodejs",
    package_json = "//:package.json",
    package_lock_json = "//:package-lock.json",
)

elm_repository(
        name = "elm_package_elm_core",
        sha256 = "6e37b11c88c89a68d19d0c7625f1ef39ed70c59e443def95e4de98d6748c80a7",
        strip_prefix = "core-1.0.5",
        urls = ["https://github.com/elm/core/archive/1.0.5.tar.gz"],
)
elm_repository(
    name = "elm_package_elm_json",
    sha256 = "d0635f33137e4ad3fc323f96ba280e45dc41afa51076c53d9f04fd92c2cf5c4e",
    strip_prefix = "json-1.1.3",
    urls = ["https://github.com/elm/json/archive/1.1.3.tar.gz"],
)
elm_repository(
        name = "elm_package_elm_browser",
        sha256 = "23f41491d325afc72649d512741fb8173725014c93e482d25bab3325555a4f59",
        strip_prefix = "browser-1.0.2",
        urls = ["https://github.com/elm/browser/archive/1.0.2.tar.gz"],
)
elm_repository(
        name = "elm_package_elm_html",
        sha256 = "73b885e0a3d2f9781b1c9bbcc1ee9ac032f503f5ef46a27da3ba617cebbf6fd8",
        strip_prefix = "html-1.0.0",
        urls = ["https://github.com/elm/html/archive/1.0.0.tar.gz"],
)
elm_repository(
        name = "elm_package_elm_time",
        sha256 = "e18bca487adec67bfe4043a33b975d81527a7732377050d0421dd86d503c906d",
        strip_prefix = "time-1.0.0",
        urls = ["https://github.com/elm/time/archive/1.0.0.tar.gz"],
)
elm_repository(
        name = "elm_package_elm_url",
        sha256 = "840e9d45d8a9bd64a7f76421a1de2518e02c7cbea7ed42efd380b4e875e9682b",
        strip_prefix = "url-1.0.0",
        urls = ["https://github.com/elm/url/archive/1.0.0.tar.gz"],
)
elm_repository(
        name = "elm_package_elm_virtual_dom",
        sha256 = "cf87286ed5d1b31aaf99c6a3368ccd340d1356b1973f1afe5f668c47e22b3b60",
        strip_prefix = "virtual-dom-1.0.2",
        urls = ["https://github.com/elm/virtual-dom/archive/1.0.2.tar.gz"],
)

