# file generated by rules_elm
load("@rules_elm//elm:defs.bzl", "elm_package")

elm_package(
    name = {{name}},
    srcs = [
        "elm.json",
    ] + glob([
        "**/*.elm",
        "**/*.js",
    ]),
    deps = {{deps}},
    package_name = {{package_name}},
    package_version = {{package_version}},
    visibility = ["//visibility:public"],
)