load("@bazel_tools//tools/build_defs/repo:http.bzl", _http_archive = "http_archive", _http_file = "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def _http_archive_maybe(**kwargs):
    maybe(_http_archive, **kwargs)

SUPPORTED_ELM_VERSION = "0.19.2"

ELM_VERSIONS = {
    SUPPORTED_ELM_VERSION: {
        "x86_64-linux": {
            "sha256": "66320d27701654fa11bd0e8d84bdf9829694d5770c8dcee2dede6160fad58737",
            "url": "https://github.com/elm/compiler/releases/download/{0}/elm-{0}-linux-x64.gz".format(SUPPORTED_ELM_VERSION),
        },
        "x86_64-darwin": {
            "sha256": "05289f0e3d4f30033487c05e689964c3bb17c0c48012510dbef1df43868545d1",
            "url": "https://github.com/elm/compiler/releases/download/{0}/elm-{0}-mac-x64.gz".format(SUPPORTED_ELM_VERSION),
        },
        "aarch64-darwin": {
            "sha256": "8b02a7fac1643b39acb87ae2a8e10f0f1534fe61940ca08ab17dfc2ac98115c8",
            "url": "https://github.com/elm/compiler/releases/download/{0}/elm-{0}-mac-arm.gz".format(SUPPORTED_ELM_VERSION),
        }
    }
}

PLATFORMS = {
    "x86_64-linux": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ]
    ),
    "x86_64-darwin": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ]
    ),
    "aarch64-darwin": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ]
    )
}

def _elm_compiler_repo_impl(repository_ctx):
    platform = repository_ctx.attr.platform
    elm_version = ELM_VERSIONS[repository_ctx.attr._elm_version]
    compatible_with = PLATFORMS[platform].compatible_with
    url = elm_version[platform]["url"]
    sha256 = elm_version[platform]["sha256"]
    repository_ctx.download(
        url = url,
        sha256 = sha256,
        output = "compiler.gz",
    )

    BUILD_TMPL = """
# file generated by repositories.bzl of @rules_elm
load("@rules_elm//elm/private:elm_toolchain.bzl", "elm_toolchain")

genrule(
    name = "extract_elm_compiler",
    srcs = [":compiler.gz"],
    outs = [ "compiler" ],
    tools = [
      "@rules_elm//tools/gzip:bin",
    ],
    cmd = "$(execpath @rules_elm//tools/gzip:bin) $(SRCS) $@",
)

elm_toolchain(
    name = "elm_toolchain_info",
    elm = ":extract_elm_compiler",
    visibility = ["//visibility:public"],
)"""

    repository_ctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            platform = platform,
            compatible_with = compatible_with,
        ),
    )

def _elm_toolchains_repo_impl(repository_ctx):

    TOOLCHAIN_TMPL = """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "{toolchain}",
    toolchain_type = "@rules_elm//elm:toolchain",
)
"""
    build_content = """
# file generated by repositories.bzl of @rules_elm

"""

    toolchain = repository_ctx.attr.toolchain

    for platform in PLATFORMS:
        compatible_with = PLATFORMS[platform].compatible_with
        build_content += TOOLCHAIN_TMPL.format(
            platform = platform,
            compatible_with = compatible_with,
            toolchain = toolchain.format(platform = platform)
        )

    repository_ctx.file("BUILD.bazel", content = build_content)

elm_toolchains_repository = repository_rule(
    _elm_toolchains_repo_impl,
    doc = "All default elm toolchains",
    attrs = {
        "toolchain": attr.string(doc = "Label of the toolchain with {platform} left as placeholder. example; @elm_{platform}//:crane_toolchain"),
        "_elm_version": attr.string(default = SUPPORTED_ELM_VERSION),
    }
)

elm_compiler_repository = repository_rule(
    _elm_compiler_repo_impl,
    doc = "Fetching external elm compiler",
    attrs = {
        "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
        "_elm_version": attr.string(default = SUPPORTED_ELM_VERSION),
    }
)

def elm_register_toolchains():

    _http_archive_maybe(
        name = "com_github_rtfeldman_node_test_runner",
        build_file_content = """load("@rules_elm//elm:defs.bzl", "elm_library")
elm_library(
    name = "node_test_runner",
    srcs = glob(["elm/src/**/*.elm"]),
    strip_import_prefix = "elm/src",
    visibility = ["//visibility:public"],
)""",
        sha256 = "c8f78d5c947cf3daf8208d207a3ceef39810c16fb89fd3a06a285792d09f6d3f",
        strip_prefix = "node-test-runner-0.19.2-0",
        urls = ["https://github.com/rtfeldman/node-test-runner/archive/refs/tags/0.19.2-0.tar.gz"],
    )

    elm_compilers_toolchain_repo_name = "elm_compiler_toolchains"

    for platform in PLATFORMS:
        elm_compiler_repository(
            name = "elm_{platform}".format(platform = platform),
            platform = platform
        )

    elm_toolchains_repository(
        name = elm_compilers_toolchain_repo_name,
        toolchain = "@elm_{platform}//:elm_toolchain_info",
    )
